### ISSUE TITLE
Update to statstat 2.0

### ISSUE THREAD

**Issue by rubak** [HectorRDB/Ecume#2]
Hi,

I'm co-developer on `spatstat` and we have been warning package maintainers using `spatstat` about the upcoming update to `spatstat` where functions are split in sub-packages and you need to change things in your package. Since you are are relatively new reverse dependency on `spatstat` I'm afraid we may have missed you in the emails. You can read the details about the transition here:
<https://github.com/rubak/spatstat.revdep/blob/main/README.md>

Let me know if you like me to process the suggested changes and make it a pull request here on GitHub.

Kind regards,
Ege

**Comment by HectorRDB** [comment]
Hi @rubak 
Thanks for informing me. I am using the transport package in the [wassertsein_permut.R](https://github.com/HectorRDB/Ecume/blob/main/R/wassertsein_permut.R) file and rely on 4 functions: `wasserstein`, `wasserstein1d`, `pp`  and `subwasserstein`. If you have time to make a PR for the necessary changes, it would be great! 
Otherwise I can take a deeper look at the transition file and implement the changes myself.

**Comment by rubak** [comment]
You only use `spatstat` very little as I can see, and I have made the few small changes needed to work with spatstat 2.0 in PR #3. I expect this version of `spatstat` to be finally accepted on CRAN next week and you can submit your new package then (I didn't bump the Ecume version in `DESCRIPTION` in the PR, so you need to do that yourself but otherwise I think my PR should make you ready for submission).

**Comment by HectorRDB** [comment]
Sorry for my last message, I got confused with another message and send something that was quite unhelpful.
Thank you for the PR, I have now merged it and will submit when spatstat 2.0 is released on CRAN.
Best
